name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: false
  push:
    branches:
      - main
    paths:
      - 'docker/**'

env:
  DOCKER_MOTIA_ORG: motiadev
  DOCKER_IMAGE_NAME: motia-docker

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        env: 
          GITHUB_SHA: ${{ github.sha::7 }}
        with:
          push: true
          tags: ${{ env.DOCKER_MOTIA_ORG }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.version || env.GITHUB_SHA }}
          file: docker/Dockerfile
          context: ./docker

      - name: Point to latest tag
        env: 
          GITHUB_SHA: ${{ github.sha::7 }}
        run: |
          docker tag ${{ env.DOCKER_MOTIA_ORG }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.version || env.GITHUB_SHA }} ${{ env.DOCKER_MOTIA_ORG }}/${{ env.DOCKER_IMAGE_NAME }}:latest
        